# Generated by Django 5.2.2 on 2025-08-27 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='clerk_id',
            new_name='clerk_user_id',
        ),
    ]
