# Generated by Django 5.2.2 on 2025-08-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0002_rename_clerk_id_customuser_clerk_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('no', 'Norwegian')], default='en', max_length=10),
        ),
    ]
