# Generated by Django 5.2.2 on 2025-09-03 17:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0003_customuser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chat_session_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
