# Generated by Django 5.2.6 on 2025-09-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0004_customuser_chat_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dark_mode',
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('pink', 'Pink'), ('purple', 'Purple')], default='dark', max_length=20),
        ),
    ]
