# Generated by Django 5.2.6 on 2025-09-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0005_remove_customuser_dark_mode_customuser_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('pink', 'Pink'), ('purple', 'Purple'), ('system', 'System')], default='dark', max_length=20),
        ),
    ]
