# Generated by Django 5.2.6 on 2025-09-28 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restAPI", "0006_alter_customuser_theme"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("user_email", models.EmailField(blank=True, max_length=254)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("PASSWORD_CHANGE", "Password Change"),
                            ("PERMISSION_CHANGE", "Permission Change"),
                            ("BULK_OPERATION", "Bulk Operation"),
                            ("ADMIN_ACTION", "Admin Action"),
                            ("FILE_UPLOAD", "File Upload"),
                            ("DATA_EXPORT", "Data Export"),
                            ("ACCESS_DENIED", "Access Denied"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("resource", models.CharField(db_index=True, max_length=100)),
                (
                    "resource_id",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_method", models.CharField(blank=True, max_length=10)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "action"],
                        name="restAPI_aud_timesta_907aa2_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="restAPI_aud_user_id_d5f78c_idx",
                    ),
                    models.Index(
                        fields=["severity", "timestamp"],
                        name="restAPI_aud_severit_12f09a_idx",
                    ),
                ],
            },
        ),
    ]
