# Generated by Django 5.2.6 on 2025-10-02 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restAPI", "0007_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("web", "Web Browser"),
                            ("mobile", "Mobile App"),
                            ("desktop", "Desktop App"),
                            ("api", "API Client"),
                        ],
                        default="web",
                        max_length=20,
                    ),
                ),
                (
                    "websocket_channel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_ping", models.DateTimeField(auto_now=True)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "n8n_conversation_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_bot_session", models.BooleanField(default=False)),
                ("bot_context", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("disconnected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_ping"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="restAPI_cha_user_id_7ef14a_idx",
                    ),
                    models.Index(
                        fields=["websocket_channel"],
                        name="restAPI_cha_websock_efbad3_idx",
                    ),
                    models.Index(
                        fields=["last_ping"], name="restAPI_cha_last_pi_76d318_idx"
                    ),
                ],
            },
        ),
    ]
