# Generated by Django 5.2.6 on 2025-10-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restAPI", "0008_add_chat_session_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="chat_session_id",
        ),
    ]
