# Generated by Django 5.2.6 on 2025-10-09 21:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restAPI", "0009_remove_old_chat_session_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("web", "Web Browser"),
                            ("desktop", "Desktop App"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="User-friendly device name (e.g., 'iPhone 15')",
                        max_length=255,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique device identifier from the device",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "push_token",
                    models.CharField(
                        blank=True,
                        help_text="Expo push token or FCM/APNS token",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("os_version", models.CharField(blank=True, max_length=50)),
                ("app_version", models.CharField(blank=True, max_length=50)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("last_active", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Set to False to revoke this device session",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Device",
                "verbose_name_plural": "User Devices",
                "ordering": ["-last_active"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="restAPI_use_user_id_da150f_idx",
                    ),
                    models.Index(
                        fields=["device_id"], name="restAPI_use_device__5fd2b9_idx"
                    ),
                    models.Index(
                        fields=["push_token"], name="restAPI_use_push_to_754d94_idx"
                    ),
                    models.Index(
                        fields=["last_active"], name="restAPI_use_last_ac_615c6e_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("device_id__isnull", False)),
                        fields=("user", "device_id"),
                        name="unique_user_device_id",
                    )
                ],
            },
        ),
    ]
