# Generated by Django 5.2.6 on 2025-09-25 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ElektriskKategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blokknummer",
                    models.CharField(
                        help_text="2-digit block number (e.g., '10', '11', '12')",
                        max_length=2,
                        unique=True,
                    ),
                ),
                (
                    "kategori",
                    models.CharField(
                        help_text="Category name (e.g., 'Kabler og ledninger')",
                        max_length=100,
                    ),
                ),
                (
                    "beskrivelse",
                    models.TextField(help_text="Detailed description and examples"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of category name",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "etim_gruppe",
                    models.CharField(
                        blank=True,
                        help_text="Related ETIM group code (e.g., 'EC000000')",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Elektrisk Kategori",
                "verbose_name_plural": "Elektriske Kategorier",
                "ordering": ["blokknummer"],
            },
        ),
        migrations.CreateModel(
            name="Jobber",
            fields=[
                (
                    "ordre_nr",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("tittel", models.CharField(blank=True, max_length=64, unique=True)),
                ("adresse", models.CharField(blank=True, max_length=256)),
                ("telefon_nr", models.CharField(blank=True, max_length=64)),
                ("beskrivelse", models.TextField(blank=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("ferdig", models.BooleanField(default=False)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        default="default/jobb_profile.png",
                        null=True,
                        upload_to="jobb_profile_image",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Jobb",
                "verbose_name_plural": "Jobber",
            },
        ),
        migrations.CreateModel(
            name="Leverandorer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "manufacturer_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("website_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Leverandør",
                "verbose_name_plural": "Leverandører",
            },
        ),
        migrations.CreateModel(
            name="JobberFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="jobb_files/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "jobb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="memo.jobber",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobberImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="jobb_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "jobb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="memo.jobber",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matriell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("el_nr", models.CharField(max_length=32, unique=True)),
                ("tittel", models.CharField(max_length=255)),
                ("info", models.TextField(blank=True)),
                ("ean_number", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "article_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "norwegian_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "english_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("height", models.CharField(blank=True, max_length=20, null=True)),
                ("width", models.CharField(blank=True, max_length=20, null=True)),
                ("depth", models.CharField(blank=True, max_length=20, null=True)),
                ("weight", models.CharField(blank=True, max_length=20, null=True)),
                ("etim_class", models.CharField(blank=True, max_length=200, null=True)),
                ("category", models.CharField(blank=True, max_length=20, null=True)),
                ("datasheet_url", models.URLField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("approved", models.BooleanField(default=True)),
                ("discontinued", models.BooleanField(default=False)),
                ("in_stock", models.BooleanField(default=True)),
                ("favorites", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "leverandor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="memo.leverandorer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matriell",
                "verbose_name_plural": "Matriell",
                "ordering": ["el_nr"],
            },
        ),
        migrations.CreateModel(
            name="JobbMatriell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("antall", models.IntegerField(default=1)),
                ("transf", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "jobb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobbmatriell",
                        to="memo.jobber",
                    ),
                ),
                (
                    "matriell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="memo.matriell"
                    ),
                ),
            ],
            options={
                "verbose_name": "JobbMatriell",
                "verbose_name_plural": "JobbMatriell",
            },
        ),
        migrations.CreateModel(
            name="Timeliste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beskrivelse", models.CharField(blank=True, max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dato", models.DateField(blank=True, null=True)),
                ("timer", models.SmallIntegerField(null=True)),
                (
                    "jobb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="memo.jobber"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "timeliste",
                "verbose_name_plural": "timelister",
            },
        ),
    ]
