# Generated by Django 5.2.2 on 2025-09-10 20:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobber',
            fields=[
                ('ordre_nr', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('tittel', models.CharField(blank=True, max_length=64, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=256)),
                ('telefon_nr', models.CharField(blank=True, max_length=64)),
                ('beskrivelse', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ferdig', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, default='default/jobb_profile.png', null=True, upload_to='jobb_profile_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jobb',
                'verbose_name_plural': 'Jobber',
            },
        ),
        migrations.CreateModel(
            name='Leverandorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leverandor',
                'verbose_name_plural': 'Leverandorer',
            },
        ),
        migrations.CreateModel(
            name='Matriell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('el_nr', models.IntegerField(blank=True, null=True, unique=True)),
                ('tittel', models.CharField(blank=True, max_length=64, unique=True)),
                ('info', models.CharField(blank=True, max_length=256)),
                ('image', models.ImageField(blank=True, default='default/matriell.png', null=True, upload_to='matriell_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leverandor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memo.leverandorer')),
            ],
            options={
                'verbose_name': 'Matriell',
                'verbose_name_plural': 'Matriell',
            },
        ),
        migrations.CreateModel(
            name='JobbMatriell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antall', models.IntegerField(default=1)),
                ('transf', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobbmatriell', to='memo.jobber')),
                ('matriell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memo.matriell')),
            ],
            options={
                'verbose_name': 'JobbMatriell',
                'verbose_name_plural': 'JobbMatriell',
            },
        ),
    ]
