# Generated by Django 5.2.2 on 2025-09-11 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobberFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='jobb_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jobb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='memo.jobber')),
            ],
        ),
        migrations.CreateModel(
            name='JobberImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='jobb_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jobb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='memo.jobber')),
            ],
        ),
        migrations.CreateModel(
            name='Timeliste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beskrivelse', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dato', models.DateField(blank=True, null=True)),
                ('timer', models.SmallIntegerField(null=True)),
                ('jobb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memo.jobber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'timeliste',
                'verbose_name_plural': 'timelister',
            },
        ),
    ]
