# Generated by Django 5.2.6 on 2025-09-25 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leverandorer",
            name="manufacturer_code",
        ),
        migrations.RemoveField(
            model_name="leverandorer",
            name="website_url",
        ),
        migrations.RemoveField(
            model_name="matriell",
            name="article_number",
        ),
        migrations.RemoveField(
            model_name="matriell",
            name="category",
        ),
        migrations.RemoveField(
            model_name="matriell",
            name="datasheet_url",
        ),
        migrations.RemoveField(
            model_name="matriell",
            name="depth",
        ),
        migrations.RemoveField(
            model_name="matriell",
            name="ean_number",
        ),
        migrations.RemoveField(
            model_name="matriell",
            name="english_description",
        ),
        migrations.RemoveField(
            model_name="matriell",
            name="etim_class",
        ),
        migrations.RemoveField(
            model_name="matriell",
            name="height",
        ),
        migrations.RemoveField(
            model_name="matriell",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="matriell",
            name="norwegian_description",
        ),
        migrations.RemoveField(
            model_name="matriell",
            name="weight",
        ),
        migrations.RemoveField(
            model_name="matriell",
            name="width",
        ),
        migrations.AddField(
            model_name="leverandorer",
            name="addresse",
            field=models.CharField(
                blank=True, help_text="Address", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="leverandorer",
            name="epost",
            field=models.EmailField(
                blank=True, help_text="Email address", max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="leverandorer",
            name="hjemmeside",
            field=models.URLField(blank=True, help_text="Website URL", null=True),
        ),
        migrations.AddField(
            model_name="leverandorer",
            name="postnummer",
            field=models.CharField(
                blank=True, help_text="Postal code", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="leverandorer",
            name="poststed",
            field=models.CharField(
                blank=True, help_text="City/postal place", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="leverandorer",
            name="telefon",
            field=models.CharField(
                blank=True, help_text="Phone number", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="matriell",
            name="bilder",
            field=models.JSONField(
                blank=True, default=list, help_text="Array of image URLs"
            ),
        ),
        migrations.AddField(
            model_name="matriell",
            name="bredde",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Width in mm",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="matriell",
            name="cpr_sertifikat",
            field=models.URLField(
                blank=True, help_text="CPR certificate URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="matriell",
            name="fdv",
            field=models.URLField(blank=True, help_text="FDV document URL", null=True),
        ),
        migrations.AddField(
            model_name="matriell",
            name="gtin_number",
            field=models.CharField(
                blank=True, help_text="GTIN/EAN code", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="matriell",
            name="hoyde",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Height in mm",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="matriell",
            name="kategori",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="memo.elektriskkategori",
            ),
        ),
        migrations.AddField(
            model_name="matriell",
            name="lengde",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Length/depth in mm",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="matriell",
            name="miljoinformasjon",
            field=models.URLField(
                blank=True, help_text="Environmental information URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="matriell",
            name="produkt_url",
            field=models.URLField(
                blank=True, help_text="Manufacturer product page URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="matriell",
            name="produktblad",
            field=models.URLField(
                blank=True, help_text="Product datasheet URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="matriell",
            name="teknisk_beskrivelse",
            field=models.TextField(
                blank=True, help_text="Detailed technical description", null=True
            ),
        ),
        migrations.AddField(
            model_name="matriell",
            name="varebetegnelse",
            field=models.CharField(
                blank=True, help_text="Product designation", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="matriell",
            name="varemerke",
            field=models.CharField(
                blank=True, help_text="Brand/manufacturer", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="matriell",
            name="varenummer",
            field=models.CharField(
                blank=True, help_text="Product number", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="matriell",
            name="vekt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight in grams",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="leverandorer",
            name="name",
            field=models.CharField(
                help_text="Company name (maps to 'navn' in JSON)",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="matriell",
            name="info",
            field=models.TextField(
                blank=True, help_text="Technical description/ETIM info"
            ),
        ),
    ]
