# Generated by Django 5.2.6 on 2025-09-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriell',
            name='favorites',
            field=models.BooleanField(default=False),
        ),
    ]
