# Generated by Django 5.2.6 on 2025-09-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_jobberfile_jobberimage_timeliste'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriell',
            name='favorites',
            field=models.BooleanField(default=False),
        ),
    ]
