# Generated by Django 5.2.6 on 2025-10-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memo", "0003_jobbmatriell_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobber",
            name="geocode_accuracy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("exact", "Exact Match"),
                    ("approximate", "Approximate Match"),
                    ("failed", "Geocoding Failed"),
                ],
                help_text="Quality of geocoding result",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobber",
            name="geocode_retries",
            field=models.SmallIntegerField(
                default=0, help_text="Number of geocoding retry attempts"
            ),
        ),
        migrations.AddField(
            model_name="jobber",
            name="geocoded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when address was last geocoded",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobber",
            name="last_geocode_attempt",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of last geocoding attempt", null=True
            ),
        ),
        migrations.AddField(
            model_name="jobber",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Latitude coordinate from geocoded address",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobber",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Longitude coordinate from geocoded address",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="jobber",
            index=models.Index(
                fields=["latitude", "longitude"], name="memo_jobber_latitud_adadc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobber",
            index=models.Index(
                fields=["ferdig", "latitude", "longitude"],
                name="memo_jobber_ferdig_5ee5bf_idx",
            ),
        ),
    ]
