# Generated by Django 5.2.6 on 2025-10-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memo", "0004_jobber_geocode_accuracy_jobber_geocode_retries_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobber",
            name="postnummer",
            field=models.CharField(
                blank=True, help_text="4-digit Norwegian postal code", max_length=4
            ),
        ),
        migrations.AddField(
            model_name="jobber",
            name="poststed",
            field=models.CharField(
                blank=True, help_text="City/postal area name", max_length=100
            ),
        ),
    ]
