# Generated by Django 5.2.6 on 2025-10-02 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memo", "0005_jobber_postnummer_jobber_poststed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveTimerSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the timer was started"
                    ),
                ),
                (
                    "last_ping",
                    models.DateTimeField(
                        auto_now=True, help_text="Last heartbeat from frontend"
                    ),
                ),
                (
                    "jobb",
                    models.ForeignKey(
                        help_text="Job being tracked",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="memo.jobber",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User who started this timer session",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Active Timer Session",
                "verbose_name_plural": "Active Timer Sessions",
                "indexes": [
                    models.Index(fields=["user"], name="memo_active_user_id_9b358d_idx")
                ],
            },
        ),
    ]
