# Generated by Django 5.2.6 on 2025-10-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memo", "0006_activetimersession"),
    ]

    operations = [
        migrations.AddField(
            model_name="activetimersession",
            name="is_paused",
            field=models.BooleanField(
                default=False, help_text="Whether the timer is currently paused"
            ),
        ),
        migrations.AddField(
            model_name="activetimersession",
            name="paused_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the timer was paused (if currently paused)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="activetimersession",
            name="total_paused_seconds",
            field=models.IntegerField(
                default=0,
                help_text="Total accumulated seconds the timer has been paused",
            ),
        ),
    ]
