# Generated by Django 5.2.6 on 2025-10-08 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memo", "0007_activetimersession_is_paused_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobberTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="jobber_tasks/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "jobb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="memo.jobber",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jobber Task",
                "verbose_name_plural": "Jobber Tasks",
                "ordering": ["-created_at"],
            },
        ),
    ]
