# Generated by Django 5.2.6 on 2025-10-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memo", "0008_jobbertask"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobberimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="jobb_images/thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="jobbertask",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="jobber_tasks/thumbnails/"
            ),
        ),
    ]
