# Streamlined pre-commit config for faster development
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3.11
        exclude: ^.*\b(migrations)\b.*$

# Temporarily disabled for faster development - can be run manually with:
# isort . && ruff check --fix . && flake8 . && mypy .
#
#  - repo: https://github.com/pycqa/isort
#    rev: 6.0.1
#    hooks:
#      - id: isort
#        exclude: ^.*\b(migrations)\b.*$
#
#  - repo: https://github.com/astral-sh/ruff-pre-commit
#    rev: v0.13.1
#    hooks:
#      - id: ruff
#        args: [--fix, --exit-non-zero-on-fix]
#        exclude: ^.*\b(migrations)\b.*$
#
#  - repo: https://github.com/pycqa/flake8
#    rev: 7.3.0
#    hooks:
#      - id: flake8
#        exclude: ^.*\b(migrations)\b.*$
#
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.18.2
#    hooks:
#      - id: mypy
#        exclude: ^.*\b(migrations)\b.*$
#        additional_dependencies:
#          - django-stubs
#          - djangorestframework-stubs
#          - types-requests
