version: '3'

services:
  django:
    image: tigertom/rest_api
    volumes:
      - /srv/docker/restapi/static:/app/static
      - /srv/docker/restapi/media:/app/media
      - /srv/docker/resrtapi/.env:/app/.env:ro
    expose:
      - "8555"

  nginx:
    image: nginx:latest
    ports:
      - "87:87"
    volumes:
      - /srv/docker/restapi/static:/srv/django/static
      - /srv/docker/restapi/media:/srv/django/media
      - /srv/docker/restapi/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - django