version: '3'

services:
  django:
    image: tigertom/rest_api
    container_name: restapi_django
    volumes:
      - /srv/docker/restAPI:/app
      - /srv/docker/restAPI/static:/app/static
      - /srv/docker/restAPI/media:/app/media
      - /srv/docker/restAPI/.env:/app/.env:ro
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - main-network

  nginx:
    image: nginx:latest
    container_name: restapi_nginx
    ports:
      - "8080:80"
    volumes:
      - /srv/docker/restAPI/static:/srv/docker/restAPI/static
      - /srv/docker/restAPI/media:/srv/docker/restAPI/media
      - /srv/docker/restAPI/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - django
    restart: unless-stopped
    networks:
      - main-network
networks:
  main-network:
    external: true
    name: main-network