version: '3'

services:
  django:
    image: tigertom/rest_api
    volumes:
      - /srv/docker/restapi/static:/app/static
      - /srv/docker/restapi/media:/app/media
      - /srv/docker/restapi/.env:/app/.env:ro
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - /srv/docker/restapi/static:/srv/docker/restapi/static
      - /srv/docker/restapi/media:/srv/docker/restapi/static
      - /srv/docker/restapi/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - django