# Generated by Django 5.2.6 on 2025-09-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_category_task_completed_at_task_description_nb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='home', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
