# Generated by Django 5.2.2 on 2025-09-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blogpost',
            name='blog_blogpo_status_aa5436_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogpost',
            name='blog_blogpo_author__e8757b_idx',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='body',
            new_name='body_markdown',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
    ]
