# Generated by Django 5.2.2 on 2025-09-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body_markdown_nb',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_nb',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_nb',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
