# Generated by Django 5.2.6 on 2025-09-19 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DockerHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('is_local', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DockerContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('restarting', 'Restarting'), ('running', 'Running'), ('removing', 'Removing'), ('paused', 'Paused'), ('exited', 'Exited'), ('dead', 'Dead')], max_length=20)),
                ('state', models.JSONField(default=dict)),
                ('ports', models.JSONField(default=list)),
                ('labels', models.JSONField(default=dict)),
                ('networks', models.JSONField(default=dict)),
                ('mounts', models.JSONField(default=list)),
                ('created_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='docker_monitor.dockerhost')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('host', 'container_id')},
            },
        ),
        migrations.CreateModel(
            name='ContainerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('memory_usage', models.BigIntegerField(blank=True, null=True)),
                ('memory_limit', models.BigIntegerField(blank=True, null=True)),
                ('memory_percent', models.FloatField(blank=True, null=True)),
                ('network_rx', models.BigIntegerField(blank=True, null=True)),
                ('network_tx', models.BigIntegerField(blank=True, null=True)),
                ('block_read', models.BigIntegerField(blank=True, null=True)),
                ('block_write', models.BigIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='docker_monitor.dockercontainer')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['container', '-timestamp'], name='docker_moni_contain_2b14ad_idx')],
            },
        ),
    ]
