# Generated by Django 5.2.6 on 2025-09-22 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerhost',
            name='architecture',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dockerhost',
            name='cpu_cores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dockerhost',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dockerhost',
            name='kernel_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dockerhost',
            name='os_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dockerhost',
            name='os_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dockerhost',
            name='total_memory',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProcessStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('memory_percent', models.FloatField(blank=True, null=True)),
                ('memory_rss', models.BigIntegerField(blank=True, null=True)),
                ('memory_vms', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('cmdline', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_stats', to='docker_monitor.dockerhost')),
            ],
            options={
                'ordering': ['-timestamp', '-cpu_percent'],
                'indexes': [models.Index(fields=['host', '-timestamp'], name='docker_moni_host_id_532a87_idx'), models.Index(fields=['host', '-cpu_percent'], name='docker_moni_host_id_b359fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('cpu_count', models.IntegerField(blank=True, null=True)),
                ('load_avg_1m', models.FloatField(blank=True, null=True)),
                ('load_avg_5m', models.FloatField(blank=True, null=True)),
                ('load_avg_15m', models.FloatField(blank=True, null=True)),
                ('memory_total', models.BigIntegerField(blank=True, null=True)),
                ('memory_available', models.BigIntegerField(blank=True, null=True)),
                ('memory_used', models.BigIntegerField(blank=True, null=True)),
                ('memory_free', models.BigIntegerField(blank=True, null=True)),
                ('memory_percent', models.FloatField(blank=True, null=True)),
                ('swap_total', models.BigIntegerField(blank=True, null=True)),
                ('swap_used', models.BigIntegerField(blank=True, null=True)),
                ('swap_free', models.BigIntegerField(blank=True, null=True)),
                ('swap_percent', models.FloatField(blank=True, null=True)),
                ('disk_total', models.BigIntegerField(blank=True, null=True)),
                ('disk_used', models.BigIntegerField(blank=True, null=True)),
                ('disk_free', models.BigIntegerField(blank=True, null=True)),
                ('disk_percent', models.FloatField(blank=True, null=True)),
                ('network_bytes_sent', models.BigIntegerField(blank=True, null=True)),
                ('network_bytes_recv', models.BigIntegerField(blank=True, null=True)),
                ('network_packets_sent', models.BigIntegerField(blank=True, null=True)),
                ('network_packets_recv', models.BigIntegerField(blank=True, null=True)),
                ('disk_read_bytes', models.BigIntegerField(blank=True, null=True)),
                ('disk_write_bytes', models.BigIntegerField(blank=True, null=True)),
                ('disk_read_count', models.BigIntegerField(blank=True, null=True)),
                ('disk_write_count', models.BigIntegerField(blank=True, null=True)),
                ('boot_time', models.DateTimeField(blank=True, null=True)),
                ('process_count', models.IntegerField(blank=True, null=True)),
                ('cpu_temperature', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_stats', to='docker_monitor.dockerhost')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['host', '-timestamp'], name='docker_moni_host_id_c0e3f0_idx')],
            },
        ),
    ]
