# Generated by Django 5.2.2 on 2025-09-13 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Llmproviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('description_nb', models.TextField(blank=True)),
                ('strengths_en', models.JSONField(blank=True, default=list)),
                ('strengths_no', models.JSONField(blank=True, default=list)),
                ('pricing', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=10)),
                ('pricing_nb', models.CharField(choices=[('Gratis', 'Gratis'), ('Betalt', 'Betalt')], default='Gratis', max_length=10)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='llmprovider_icons/')),
                ('tags', models.ManyToManyField(blank=True, related_name='llmproviders', to='components.tag')),
            ],
            options={
                'verbose_name': 'Llmprovider',
                'verbose_name_plural': 'Llmproviders',
            },
        ),
    ]
